# Generated by Django 4.2.1 on 2023-09-12 17:19

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videopost', '0002_remove_video_thumbnail_video_uploaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('totalvalue', models.IntegerField(default=0)),
                ('clickvalue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TagsMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videopost.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('video', cloudinary.models.CloudinaryField(max_length=255)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='tagsmap',
            name='videoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videopost.videos', to_field='title'),
        ),
    ]
