# Generated by Django 4.2.1 on 2023-09-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videopost', '0004_rename_tags_tag_rename_tagsmap_tagmap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='clickvalue',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='totalvalue',
        ),
        migrations.CreateModel(
            name='whenClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tagid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videopost.tag')),
            ],
        ),
    ]
