# Generated by Django 4.2.1 on 2023-09-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videopost', '0007_tag_clickvalueperday_tag_uploadedperday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='clickvalueperday',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='uploadedperday',
        ),
    ]
