# Generated by Django 4.2.1 on 2023-10-11 02:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0008_remove_tag_clickvalueperday_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="whenclick",
            managers=[
                ("query", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="video",
            name="tokenid",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="uploader",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
