# Generated by Django 4.2.1 on 2023-10-15 08:41

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0009_alter_whenclick_managers_video_tokenid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "accountid",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="video",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="onedaydelete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tagmap",
            name="videoid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="videopost.video",
                to_field="video",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=cloudinary.models.CloudinaryField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="uploader",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="videopost.account",
            ),
            preserve_default=False,
        ),
    ]
