# Generated by Django 4.2.1 on 2023-10-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0010_account_video_address_video_onedaydelete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="acc",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
