# Generated by Django 4.2.1 on 2023-10-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0011_account_acc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(max_length=1)),
            ],
        ),
    ]
