# Generated by Django 4.2.1 on 2023-10-15 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0012_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
