# Generated by Django 4.2.1 on 2023-10-15 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0013_delete_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="acc",
        ),
    ]
