# Generated by Django 4.2.1 on 2023-10-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0014_remove_account_acc"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="privatekey",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
