# Generated by Django 4.2.1 on 2023-10-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0015_account_privatekey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="accountid",
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="privatekey",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
