# Generated by Django 4.2.1 on 2023-10-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0018_rename_walletadress_account_walletaddress"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="whenclick",
            managers=[],
        ),
        migrations.AddField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="videopost.tag"
            ),
        ),
    ]
