# Generated by Django 4.2.1 on 2023-10-25 03:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0020_account_name_alter_account_walletaddress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="address",
        ),
    ]
