# Generated by Django 4.2.1 on 2023-10-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0021_remove_video_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="address",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
