# Generated by Django 4.2.1 on 2023-10-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0022_video_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
