# Generated by Django 4.2.1 on 2023-10-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0023_alter_video_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="tokenid",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
