# Generated by Django 4.2.1 on 2023-10-26 02:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0025_devicemap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagmap",
            name="videoid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videopost.video"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
