# Generated by Django 4.2.1 on 2023-10-26 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0026_alter_tagmap_videoid_alter_video_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("browser", models.CharField(max_length=15)),
                (
                    "accountid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videopost.account",
                    ),
                ),
            ],
        ),
    ]
