# Generated by Django 4.2.1 on 2023-10-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0027_browsermap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="uploader",
            field=models.ManyToManyField(
                blank=True, related_name="uploader", to="videopost.account"
            ),
        ),
    ]
