# Generated by Django 4.2.1 on 2023-11-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0028_alter_video_uploader"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbsup",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
