# Generated by Django 4.2.1 on 2023-11-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0029_video_description_video_thumbsup_video_views_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="ispublic",
            field=models.BooleanField(default=True),
        ),
    ]
