# Generated by Django 4.2.1 on 2023-12-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0030_video_ispublic"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
