# Generated by Django 4.2.1 on 2023-12-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videopost", "0031_video_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
